<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="formulario.css">
    <title>Formulario</title>
    <style>
    *{
    margin :0;
    padding: 0;
}
#titulo{
    font-family: sans-serif;
    color: rgb(245, 245, 240);
    margin-left: 7% ;
}#subtitulo{
    font-family: sans-serif;
    color: rgb(195, 221, 220);
    margin-left: 10% ;
}

fieldset{
    border: 0;
}
body{
    background-color:#465a5e;
    font-family: sans-serif;
    font-size: 1em;
    color:rgb(182, 217, 228);
    margin-left: 36%;
    margin-top: 2%;
    justify-content: center;

}
input,select,textarea,button{
    border-radius: 5px;
}
.campo{
    margin-bottom: 1em;
}
.campo label{
    margin-bottom: 0.2em;
    color:rgb(182, 217, 228);
    display: block;
}
fieldset.grupo.campo{
    float: left;
    margin-right: 1em;
}
.campo input[type ="texte"],campo input[type ="emeial"],campo input[type ="data"],.campo select , .campo textarea{
    padding: 0.2em;
    border: 1px solid #9594d4;
    box-shadow: 2px 2px 2px #403f69;
}
 .campo select option{
    padding-right: 1em;
 }
 .campo input:focus, .campo select:focus,.campo textarea:focus,.campo data:focus{
    background-color: #01091b;
 }
.botao{
    font-size: 1.2em;
    background-color: #403f69;
    border: 0;
    margin-bottom: 1em;
    color:rgb(255, 255, 255);
    padding: 0.2em 0.6em;
    box-shadow: 2px 2px 2px;
    text-shadow: 1px 1px 1px rgb(40, 31, 65);
    position: absolute;
    top: 90%;
    left:50%;
    margin-right: -50%;


}
    </style>
</head>
<body>
    <div>
        <h1 id = "titulo">Cadastro de Usuario </h1>
        <p id ="subtitulo">Preencha os campos a baixo:</p>
        <br>
    </div>
    <form >
        <fieldset class ="grupo">
            <div class="campos">
                <label for="Nome">Nome</label>
                <input type ="text" name="Nome" id = "Nome "required>
            </div>
            <div class="campos">
                <label >Sobrenome</label>
                <input type ="text" name="Sobrenome" id = "Sobrenome "required>
            </div>
            <div class="campos">
                <label for="Email" >Email</label>
                <input type ="email" name="email" id = "email"required>
            </div>
            <div class="campos">
                <label >Qual o seu Genêro:</label>
                <br>
                <label for = "Genêro">
                    <input type="radio" name = "Masculino" value = "Homem">Masculino
             <br>
                    <input type="radio" name = "Femino" value = "Mulher">Feminino
               <br>
                    <input type="radio" name = "Lgbt" value = "LGBTQIA+">Lgbtqia+
                </label>
            </div>
            <div class="campos">
                <label for="Região">Região</label>
                <select>
                    <option selected disabled ="">Escolha</option>
                    <option>Centro-Oeste</option>
                    <option>Nordeste</option>
                    <option>Norte</option>
                    <option>Sudeste</option>
                    <option>Sul</option>
                </select>                
                <br>
                <p>Insira sua data de nascimento : </p>
                <div class="campos"></div>
                <label for="data" >
                    <input type="date" name ="Data" id ="Idade">
                </label>
            </div>
            </div>

        </fieldset>
        <button type = "submit" id ="button">Concluido</button>
    </form>
</body>
</html>
